### ISSUE TITLE
Some error occures.

### ISSUE THREAD

**Issue by greenhandzdl** [fengyanwan/genshin_cook#1]
```
Traceback (most recent call last):
  File "D:\Users\20292\Documents\GitHub\Genshin_cook\genshin_impact_auto_cook.py", line 47, in <module>
    img = pyautogui.screenshot()            # 截图
  File "C:\Users\20292\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyscreeze\__init__.py", line 144, in wrapper
    raise PyScreezeException('The Pillow package is required to use this function.')
pyscreeze.PyScreezeException: The Pillow package is required to use this function.
```

**Comment by fengyanwan** [comment]
The Pillow package is required to use this function.
需要安装 Pillow 模块，`pip install pillow`

最近没研究这个了，很多安装包可能有依赖关联之类的，一般按提示来就行

**Comment by greenhandzdl** [comment]
Thanks 👍, I've try it.
